name: CD with AWS CDK

on:
  push:
    branches:
      - dev
      - homolog
      - prod

jobs:
  DeploytoAWS:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setting AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/CDKRole
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install CDK dependencies
        working-directory: ./
        run: |
          npm install -g aws-cdk
          cd iac
          pip install -r requirements.txt

      - name: CDK Deploy
        working-directory: ./iac
        run: |
          cdk synth
          cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ var.AWS_REGION }}

