name: CD

on:
  push:
    branches:
      - dev
      - homolog
      - prod

jobs:
  DeploytoAWS:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setting AWS Credentials
        uses: aws configure --profile default
        with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_default_region: ${{ secrets.AWS_REGION }}

      - name: Install CDK dependencies
        working-directory: ./
        run: |
          npm install -g aws-cdk
          cd iac
          pip install -r requirements.txt

      - name: CDK Deploy
        working-directory: ./iac
        run: |
          cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION
          cdk synth
          cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}

