name: CD

on:
  push:
    branches:
      - dev
      - homolog
      - prod

jobs:
  Deploy_to_AWS:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get the branch name from the PR
        run: |
          echo "STACK_NAME=ApaeLeilaoStack${{ github.ref_name }}" >> $GITHUB_ENV
          echo "BUCKET_NAME=apae-leilao-bucket-${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install CDK dependencies
        run: |
          sudo npm install -g aws-cdk
          cd iac
          pip3 install -r requirements.txt

      - name: CDK Deploy
        run: |
          cd iac
          cdk context --reset
          cdk context --global aws:region=$AWS_REGION aws:account=$AWS_ACCOUNT_ID
          cdk synth
          cdk deploy --require-approval never
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SES_REGION: ${{ secrets.SES_REGION }}
          SES_SENDER: ${{ secrets.SES_SENDER }}
          STAGE: ${{ github.ref_name }}
          STACK_NAME: ${{ env.STACK_NAME }}
          BUCKET_NAME: ${{ env.BUCKET_NAME }}
