name: CD

on:
  push:
    branches:
      - dev
      - homolog
      - prod

jobs:
  Deploy_to_AWS:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setting AWS Credentials
        run: |
          aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}

      - name: Install CDK dependencies
        working-directory: ./
        run: |
          sudo npm install -g aws-cdk
          cd iac
          sudo pip3 install -r requirements.txt

      - name: CDK Deploy
        working-directory: ./iac
        run: |
          cdk synth
          cdk deploy --require-approval never
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SES_REGION: ${{ vars.SES_REGION }}
          SES_SENDER: ${{ vars.SES_SENDER }}
          STAGE: ${{ github.ref_name }}
          STACK_NAME: ${{ env.STACK_NAME }}

