name: CD

on:
  push:
    branches:
      - dev
      - homolog
      - prod

jobs:
  Deploy_to_AWS:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Get Stack and Bucket name
        run: |
          echo "STACK_NAME=ApaeLeilaoStack${{ github.ref_name }}" >> $GITHUB_ENV
          echo "BUCKET_NAME=apae-leilao-bucket-${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Install CDK dependencies
        run: |
          npm install -g aws-cdk
          cd iac
          pip install -r requirements.txt

      - name: CDK Synth
        run: |
          cd iac
          cdk synth
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SES_REGION: ${{ vars.SES_REGION }}
          SES_SENDER: ${{ vars.SES_SENDER }}
          STAGE: ${{ github.ref_name }}
          STACK_NAME: ${{ env.STACK_NAME }}
          BUCKET_NAME: ${{ env.BUCKET_NAME }}


      - name: CDK Deploy
        run: |
          cd iac
          cdk deploy --require-approval never
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SES_REGION: ${{ vars.SES_REGION }}
          SES_SENDER: ${{ vars.SES_SENDER }}
          STAGE: ${{ github.ref_name }}
          STACK_NAME: ${{ env.STACK_NAME }}
          BUCKET_NAME: ${{ env.BUCKET_NAME }}

